### ISSUE TITLE
Meta: Complete Marketing Building Block Kit Patterns

### ISSUE THREAD

**Issue by backlineint** [backlineint/foundation_patterns#24]
- [X] Marketing site content section
- [X] Marketing site feature section
- [X] Marketing site footer
- [X] Marketing site hero section
- [ ] Marketing site 3 up feature section
- [X] Responsive social media section
- [X] Top bar with animation
- [X] Read more content / button link
- [X] Vertical testimonial block
- [ ] Featured testimonials
- [X] Testimonial Slider
- [ ] Product Feature Section
- [X] Pricing table
- [ ] Top nav bar with centered logo
- [ ] App feature Section
